import { HomeIcon } from "@sanity/icons/Home";
import { defineArrayMember, defineField, defineType } from "sanity";
import { CURRENCIES, LISTING_STATUSES, PROPERTY_TYPES, REGIONS } from "../options";

export const property = defineType({
  name: "property",
  title: "Listing",
  type: "document",
  icon: HomeIcon,
  fieldsets: [
    { name: "location", title: "Location", options: { columns: 2 } },
    { name: "details", title: "Details", options: { columns: 2 } },
  ],
  groups: [
    { name: "content", title: "Listing", default: true },
    { name: "media", title: "Photos" },
    { name: "seo", title: "Search & sharing" },
  ],
  fields: [
    defineField({
      name: "name",
      title: "Property name",
      type: "string",
      group: "content",
      description: "How the listing is titled on cards and on its own page.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Web address",
      type: "slug",
      group: "content",
      description: "The listing's own page, e.g. /property/zanzibar-stone-villa. Press Generate.",
      options: { source: "name", maxLength: 80 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      group: "content",
      initialValue: "available",
      description:
        "Sold and reserved listings stay on the site with a label, so their address keeps working. Hidden takes a listing off the site without deleting it.",
      options: { list: [...LISTING_STATUSES], layout: "radio" },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "price",
      title: "Price",
      type: "number",
      group: "content",
      fieldset: "details",
      description:
        "Amara quotes in US dollars. Enter the plain number — no symbols or commas. Visitors see it converted into their own currency automatically.",
      validation: (rule) => rule.required().min(0),
    }),
    defineField({
      name: "currency",
      title: "Quoted in",
      type: "string",
      group: "content",
      fieldset: "details",
      initialValue: "USD",
      description: "Leave as USD unless this listing is genuinely priced in a local currency.",
      options: { list: CURRENCIES },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "type",
      title: "Property type",
      type: "string",
      group: "content",
      fieldset: "details",
      options: { list: [...PROPERTY_TYPES] },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "beds",
      title: "Bedrooms",
      type: "number",
      group: "content",
      fieldset: "details",
      validation: (rule) => rule.required().min(0).integer(),
    }),
    defineField({
      name: "city",
      title: "Neighbourhood, city",
      type: "string",
      group: "content",
      fieldset: "location",
      description: "e.g. Camps Bay, Cape Town",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "country",
      title: "Country",
      type: "string",
      group: "content",
      fieldset: "location",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "region",
      title: "Region",
      type: "string",
      group: "content",
      description: "Used by May when a visitor searches by region.",
      options: { list: [...REGIONS] },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "tag",
      title: "Highlight",
      type: "string",
      group: "content",
      description: "One short selling point, e.g. “Ocean-facing”.",
    }),
    defineField({
      name: "baths",
      title: "Bathrooms",
      type: "number",
      group: "content",
      fieldset: "details",
      description: "Optional.",
      validation: (rule) => rule.min(0),
    }),
    defineField({
      name: "area",
      title: "Internal area (m²)",
      type: "number",
      group: "content",
      fieldset: "details",
      description: "Optional.",
      validation: (rule) => rule.min(0),
    }),
    defineField({
      name: "summary",
      title: "One-line summary",
      type: "text",
      group: "content",
      rows: 2,
      description:
        "A single sentence, shown under the name on the listing's page and used as its search-result description.",
      validation: (rule) => rule.max(200).warning("Keep it to a sentence."),
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "simpleText",
      group: "content",
      description: "The longer write-up on the listing's own page.",
    }),
    defineField({
      name: "amenities",
      title: "Features",
      type: "array",
      group: "content",
      description: "One per line — e.g. Private pool, Ocean view, Staff quarters.",
      of: [defineArrayMember({ type: "string" })],
      options: { layout: "tags" },
      validation: (rule) => rule.unique(),
    }),
    defineField({
      name: "art",
      title: "Main photo or artwork",
      type: "art",
      group: "media",
      description: "The first frame on the listing card.",
    }),
    defineField({
      name: "gallery",
      title: "More photos",
      type: "array",
      group: "media",
      description: "Extra photos or scenes. Visitors page through them with the << >> buttons on the card.",
      of: [defineArrayMember({ type: "art" })],
    }),
    defineField({
      name: "badge",
      title: "Label on artwork",
      type: "string",
      group: "media",
      description: "Optional short label printed over the card's artwork, e.g. EPISODES.",
      validation: (rule) => rule.max(24),
    }),
    defineField({
      name: "sortOrder",
      title: "Display order",
      type: "number",
      group: "content",
      description: "Lower numbers appear first in listing grids.",
    }),
    defineField({
      name: "seo",
      title: "Search & sharing",
      type: "seo",
      group: "seo",
      description: "Optional. Left empty, the name and summary above are used.",
    }),
  ],
  orderings: [
    {
      title: "Display order",
      name: "sortOrderAsc",
      by: [{ field: "sortOrder", direction: "asc" }],
    },
    {
      title: "Price, high to low",
      name: "priceDesc",
      by: [{ field: "price", direction: "desc" }],
    },
    { title: "Name", name: "nameAsc", by: [{ field: "name", direction: "asc" }] },
  ],
  preview: {
    select: {
      title: "name",
      city: "city",
      country: "country",
      price: "price",
      currency: "currency",
      status: "status",
      media: "art.image",
    },
    prepare: ({ title, city, country, price, currency, status, media }) => ({
      title,
      subtitle: [
        status && status !== "available" ? status.toUpperCase() : null,
        typeof price === "number" ? `${currency ?? "USD"} ${price.toLocaleString("en-US")}` : null,
        [city, country].filter(Boolean).join(", "),
      ]
        .filter(Boolean)
        .join(" · "),
      media: media ?? HomeIcon,
    }),
  },
});
